// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';

/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4qndSXIbncYkU_lU0cjycSaOzU-Nq8Jw',
    appId: '1:488153183693:web:62f46125bec623467a8084',
    messagingSenderId: '488153183693',
    projectId: 'studenttawsel',
    authDomain: 'studenttawsel.firebaseapp.com',
    storageBucket: 'studenttawsel.appspot.com',
    measurementId: 'G-ZCDSFP36S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKgGs-ZQViTxfITLapGkePU9FZkQvcH6U',
    appId: '1:39236968102:android:55d30c1ff55b7832565e67',
    messagingSenderId: '39236968102',
    projectId: 'student-tawsel-c6662',
    storageBucket: 'student-tawsel-c6662.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9PvoFIrlw0uQ84h_8GOg0IKFtTSv-zjQ',
    appId: '1:39236968102:ios:9da17b1aea535e70565e67',
    messagingSenderId: '39236968102',
    projectId: 'student-tawsel-c6662',
    storageBucket: 'student-tawsel-c6662.appspot.com',
    iosBundleId: 'com.example.studentTawsel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Xu6kjzICHECjMnGRWRytxqDWxtjeZhs',
    appId: '1:488153183693:ios:8e378de7b29f461a7a8084',
    messagingSenderId: '488153183693',
    projectId: 'studenttawsel',
    storageBucket: 'studenttawsel.appspot.com',
    iosBundleId: 'com.example.studentTawsel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4qndSXIbncYkU_lU0cjycSaOzU-Nq8Jw',
    appId: '1:488153183693:web:9a6df5d37473623b7a8084',
    messagingSenderId: '488153183693',
    projectId: 'studenttawsel',
    authDomain: 'studenttawsel.firebaseapp.com',
    storageBucket: 'studenttawsel.appspot.com',
    measurementId: 'G-4LJWWTPG2C',
  );
}